name: Build documentation

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows it to be called from another workflow
  workflow_call:

env:
  # Directory that will be uploaded as artifact
  PUBLISH_DIR: ./_build/html

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          # fenics-dolfin on conda-forge starts at 3.8
          python-version: "3.8.*"

      - name: Build the book
        shell: bash -l {0}
        run: |
          python3 -m pip install sphinx-autoapi jupyter-book
          jupyter book build .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.PUBLISH_DIR }}
          name: docs
