on:
  push:
    branches:
      - master
    tags:
      - "refs/tags/v*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build sdist
        run: |
          python setup.py sdist
          echo ref: {{ github.ref }}

      - name: Check that tag matches version
        run: |
          setup_version=$(grep ^version setup.cfg | cut -d = -f 2 | tr -d "[:space:]")
          tag_version=$(sed -e 's|^refs/tags/v||' <<<{{ github.ref }})
          if [[ $tag_version != $setup_version ]]; then
            echo "'$tag_version' (tag) != '$setup_version' (setup.cfg)"
            exit 1
          fi

      - name: Publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
