on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          # fenics-dolfin on conda-forge starts at 3.8
          python-version: 3.8.*

      - name: Set environment
        run: |
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
          pip install coverage

      - name: Run tests
        run: |
          coverage run --parallel-mode -m pytest -v test

      - name: Run regression tests
        run: |
          demo/regression-test.sh --coverage

      - name: Coverage report
        run: |
          coverage combine
          coverage report -m --include "block/*"
