on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          # fenics-dolfin on conda-forge starts at 3.8
          python-version: "3.8.*"

      - name: Set environment
        run: |
          echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
          pip install coverage

      - name: Run tests
        run: |
          coverage run --parallel-mode --branch -m pytest -v test

      - name: Run regression tests
        run: |
          demo/regression-test.sh --coverage

      - name: Coverage report
        run: |
          coverage combine
          coverage report -m --include "block/*"
          coverage xml --include "block/*" --quiet

      - name: Coverage PR comment
        if: github.event_name == 'pull_request'
        continue-on-error: true # it fails but only after doing its thing
        uses: 5monkeys/cobertura-action@master
        with:
          #path: src/test.xml
          #minimum_coverage: 75
          skip_covered: false
          minimum_coverage: 50
          fail_below_threshold: false
          show_line: true
          show_branch: true
          show_missing: true
          link_missing_lines: true
          #link_missing_lines_source_dir: 
          only_changed_files: true

